# Remove these env vars from the main workflow file
env:
  KIT_NAME: vault
  # Remove these AWS related env vars
  # AWS_REGION: us-east-1 
  # AWS_BUCKET: genesis-pipeline

# Update the build-kit job to include pushing the version commit
jobs:
  build-kit:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for tags
      
      - id: version
        uses: ./.github/actions/version-manager
        with:
          bump_type: ${{ inputs.version_bump || 'patch' }}
          
      - name: Push version change
        run: |
          git push origin HEAD
          git tag "v${{ steps.version.outputs.new_version }}"
          git push origin "v${{ steps.version.outputs.new_version }}"
          
      # Rest of the job remains the same...